### ISSUE TITLE
error running in jupyter notebook

### ISSUE THREAD

**Issue by dlingling** [dsavoiu/kafe#6]
Dear developer,

Thank you for providing such a good tool. I like it very much. However, when I running it on the Jupyter Notebook, I met with the following errors:
```
---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-3-126afbba2fd9> in <module>()
     34 #contour2.savefig('kafe_example0_contour2.pdf')
     35 #contour3.savefig('kafe_example0_contour3.pdf')
---> 36 profile=my_fit.plot_profile(2)
     37 #profile.savefig('kafe_example0_profile.pdf')
     38 

/home/jialing/anaconda3/lib/python3.5/site-packages/kafe-1.3.0-py3.5.egg/kafe/fit.py in plot_profile(self, parid, n_points, color, alpha, show, axes)
   1360         # tmp_ax.scatter(xval, yval, marker='+', label='parameter values')
   1361         # get profile
-> 1362         xp, yp = self.minimizer.get_profile(id, n_points)
   1363         self.profiles.append([id, xp, yp])  # store this result
   1364         # plot (smoothed) profile

/home/jialing/anaconda3/lib/python3.5/site-packages/kafe-1.3.0-py3.5.egg/kafe/iminuit_wrapper.py in get_profile(self, parameter, n_points)
    522 
    523         # save the old stdout stream
--> 524         old_out_stream = os.dup(sys.stdout.fileno())
    525         os.dup2(self.out_file.fileno(), sys.stdout.fileno())
    526 

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/ipykernel/iostream.py in fileno(self)
    357 
    358     def fileno(self):
--> 359         raise UnsupportedOperation("IOStream has no fileno.")
    360 
    361     def write(self, string):

UnsupportedOperation: IOStream has no fileno.
```

If I commented it out, everything is fine, do you know how to avoid this and is it necessary to keep it in the file?

Thank you in advance!

**Comment by dsavoiu** [comment]
Thanks for reporting this!

The issue should be fixed now and will be part of the upcoming kafe release 1.3.0. See below for details.

**Note**: I haven't tested _kafe_ with Jupyter Notebooks yet, so it is possible that some issues remain.


### Some background on this issue

Since _kafe_ relies on _MINUIT,_ it ultimately calls the minimization routines contained in the external _MINUIT_ library (either the one in ROOT, or the one in [iminuit](https://github.com/iminuit/iminuit)), which reports on the minimization by writing directly to standard output.

In order to store the output of these external programs in a separate files, _kafe_ redirects the standard output stream to a file before the call to _MINUIT,_ and switches back to standard out after MINUIT returns.

This is done by using the redirection functionality provided by the `os` module (`os.dup` and `os.dup2`), mainly in order to avoid having operating-system-specific code. These methods reroute the output on a very low level, using _file descriptors_ on Linux and _handles_ on Windows.
Luckily, the `os` module handles both via the `fileno()` method implemented by each I/O stream.

As I understand it, when working in a Jupyter Notebook, the standard input and output streams are replaced by a custom implementation, which is specific to Jupyter/IPython/ipykernel. This is presumably necessary in order to communicate with the Python kernel that is currently active.

This implementation, however, does not use file descriptors directly, so there is no `fileno()` available for the output stream, which is why the error shows up in Jupyter.

### Temporary Fix

For now, I committed a fix which checks for a `fileno()` method before redirecting the output. If it doesn't find one, the output is not redirected. A side effect of this is that you will see output from _MINUIT_ when running in the Jupyter Notebook.

@dlingling Commenting out every line containing a call to `os.dup` or `os.dup2` should be fine as a temporary fix, as long as you do it consistently. Forgetting a call could result in opening more file descriptors than necessary, or even losing the output stream completely...
In any case, the newest version on the [release-v1.3](https://github.com/dsavoiu/kafe/tree/release-v1.3) branch should now work in Jupyter Notebooks as well.
